sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t reghoward/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reghoward/docker-react npm run test