sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t reghoward/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reghoward/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react-project"
  env: "Docker-react-project-env"
  bucket_name: "elasticbeanstalk-us-east-1-862608177497"
  bucket_path: "Docker-react-project"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"